# Generated by Django 5.2.5 on 2025-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('maPhongBan', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã phòng ban')),
                ('tenPhongBan', models.CharField(help_text='Tên của phòng ban', max_length=255, verbose_name='Tên phòng ban')),
                ('moTa', models.TextField(blank=True, help_text='Mô tả chi tiết về phòng ban', null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'db_table': 'PhongBan',
                'ordering': ['maPhongBan'],
                'managed': True,
            },
        ),
    ]
